[package]
name = "ebod"
version = "0.1.0"
edition = "2024"
author = "Sivaprakash P"

[dependencies]
chrono = "0.4.42"
clap = {version = "4.5.54", features=["derive"]}
hf = "0.5.1"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
